# -*- coding: utf-8 -*-
"""exercicio-pagina-77.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Vw_wLEdwml_jalTWkotxuWER13LOVuG
"""

def soma(arr) -> int:
  tamanho_array = len(arr)
  if tamanho_array == 1:
    return arr[0]

  number = arr.pop(tamanho_array - 1)
  return number + soma(arr)


soma([1,2,3])

def count_items(list):
  tamanho_array = len(list)
  if tamanho_array == 0:
    return 0

  list.pop(tamanho_array - 1)
  return 1 + count_items(list)

count_items([1,2,3])

def greater_number_in_list(list):
  list_length = len(list)
  if list_length == 1:
    return list[0]

  half_index = list_length // 2
  first_half_greater = greater_number_in_list(list[half_index:])
  second_half_greater = greater_number_in_list(list[:half_index])
  return first_half_greater if first_half_greater >= second_half_greater else second_half_greater

greater_number_in_list([12,1,2,3,9])